CREATE SCHEMA IF NOT EXISTS PETSHOP;
USE PETSHOP;

CREATE TABLE IF NOT EXISTS PEOPLE (
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
);

CREATE TABLE IF NOT EXISTS STAFF (
);

CREATE TABLE IF NOT EXISTS ORDER (
);

CREATE TABLE IF NOT EXISTS ORDER_DETAIL (
);

CREATE TABLE IF NOT EXISTS SERVICE (
);

CREATE TABLE IF NOT EXISTS PRODUCT (
);